/** Canonical list of `namespace.action` tool ids for MCP CLI and configuration resolution. */
export const ACCEPTED_TOOLS: readonly string[] = [
  'business-unit.read',
  'business-unit.create',
  'business-unit.update',
  'products.read',
  'products.create',
  'products.update',
  'project.read',
  'product-search.read',
  'category.read',
  'category.create',
  'category.update',
  'channel.read',
  'channel.create',
  'channel.update',
  'product-selection.read',
  'product-selection.create',
  'product-selection.update',
  'order.read',
  'order.create',
  'order.update',
  'cart.read',
  'cart.create',
  'cart.update',
  'customer.create',
  'customer.read',
  'customer.update',
  'customer-group.read',
  'customer-group.create',
  'customer-group.update',
  'quote.read',
  'quote.create',
  'quote.update',
  'quote-request.read',
  'quote-request.create',
  'quote-request.update',
  'staged-quote.read',
  'staged-quote.create',
  'staged-quote.update',
  'standalone-price.read',
  'standalone-price.create',
  'standalone-price.update',
  'product-discount.read',
  'product-discount.create',
  'product-discount.update',
  'cart-discount.read',
  'cart-discount.create',
  'cart-discount.update',
  'discount-code.read',
  'discount-code.create',
  'discount-code.update',
  'product-type.read',
  'product-type.create',
  'product-type.update',
  'bulk.create',
  'bulk.update',
  'inventory.read',
  'inventory.create',
  'inventory.update',
  'store.read',
  'store.create',
  'store.update',
  'review.read',
  'review.create',
  'review.update',

  'tax-category.read',
  'tax-category.create',
  'tax-category.update',

  'shipping-methods.read',
  'shipping-methods.create',
  'shipping-methods.update',

  'payments.read',
  'payments.create',
  'payments.update',

  'zone.read',
  'zone.create',
  'zone.update',

  'product-tailoring.read',
  'product-tailoring.create',
  'product-tailoring.update',

  'payment-methods.read',
  'payment-methods.create',
  'payment-methods.update',

  'recurring-orders.read',
  'recurring-orders.create',
  'recurring-orders.update',

  'shopping-lists.read',
  'shopping-lists.create',
  'shopping-lists.update',

  'extensions.read',
  'extensions.create',
  'extensions.update',

  'subscriptions.read',
  'subscriptions.create',
  'subscriptions.update',

  'custom-objects.read',
  'custom-objects.create',
  'custom-objects.update',

  'types.read',
  'types.create',
  'types.update',

  'payment-intents.update',

  'transactions.read',
  'transactions.create',
];
